###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
    "name": "Andres Marin",
    "telefone": "11235689784",
    "email": "andresmarin@gmail.com",
    "agepet":2,
    "race":"Pastor Alaman"
}
###
GET  http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/65089986ef8c5399232386b9 HTTP/1.1

###
PUT http://localhost:9000/api/users/65089986ef8c5399232386b9 HTTP/1.1
Content-Type: application/json 

{
    "name": "Andres Marin",
    "telefone": "11235689784",
    "email": "andresmarin@gmail.com",
    "agepet":2,
    "race":"Pastor Alaman"
}

### 
DELETE http://localhost:9000/api/users/650b8de570dd66895ddb210c HTTP/1.1